name: docsy_markdown
description: Markdown import/export adapter for Docsy.
version: 0.1.0
repository: https://github.com/AstroDevs-Team/Docsy
issue_tracker: https://github.com/AstroDevs-Team/Docsy/issues
homepage: https://github.com/AstroDevs-Team/Docsy#readme

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  docsy: ^0.1.0
  markdown: ^7.2.2

dev_dependencies:
  flutter_lints: ^4.0.0