name: docsy_toolbar
description: A customizable toolbar for the Docsy Flutter editor. Includes ready-made buttons (bold, italic, headings, lists, links, images) with easy integration.
version: 0.1.1
repository: https://github.com/AstroDevs-Team/Docsy
issue_tracker: https://github.com/AstroDevs-Team/Docsy/issues
homepage: https://github.com/AstroDevs-Team/Docsy#readme

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  docsy: ^0.1.1

dev_dependencies:
  flutter_lints: ^4.0.0