name: docsy_example
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  docsy:
    path: ../docsy
  docsy_toolbar:
    path: ../docsy_toolbar
  
dev_dependencies:
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/example_document.json
