name: docsy_example
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  docsy:
    path: ../docsy
  docsy_toolbar:
    path: ../docsy_toolbar

flutter:
  uses-material-design: true
  assets:
    - assets/example_document.json