name: docsy_html
description: Markdown import and export support for Docsy, the modular Flutter WYSIWYG editor. Convert documents seamlessly between Docsy and Markdown.
version: 0.1.1
repository: https://github.com/AstroDevs-Team/Docsy
issue_tracker: https://github.com/AstroDevs-Team/Docsy/issues
homepage: https://github.com/AstroDevs-Team/Docsy#readme

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  docsy: ^0.1.1
  html: ^0.15.4

dev_dependencies:
  flutter_lints: ^4.0.0
