name: docsy_html
description: HTML import/export adapter for Docsy.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  docsy:
    path: ../docsy
  html: ^0.15.4

dev_dependencies:
  flutter_lints: ^4.0.0
