name: docsy
description: Core Flutter WYSIWYG editor engine and widgets for Docsy.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  characters: ^1.3.0
  meta: ^1.12.0
  uuid: ^4.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
